basic_settings:
  site_title: Hai Phan.
  site_description: Multidisciplinary Designer
  site_email: work@haiphan.design
  favicon_image: /images/favicon.png

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Works'
      url: '/works/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about'
    # - title: 'Contact'
    #   url: '/contact'
    - title: 'Lab'
      url: '/lab'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: multidisciplinary-designer based in melbourne. work international.

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 10

social_settings:
  facebook_url: 'https://www.facebook.com/jekyllthemes/'
  twitter_url: 'https://twitter.com/jekyllthemesio'
  instagram_url: 'http://instagram.com'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: 'http://tumblr.com'
  dribbble_url: 'http://dribbble.com'
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#292929'
  text_regular_color: '#292929'
  text_light_color: 'darkgray'
  accent_color: '#d50f25'
  border_color: '#dddddd'
  overlay_background_color: '#F2784B'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'
  grid_color: '#eeeeee'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  root_size: 15
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  menu:
    small_size: 3
    medium_size: 1
    large_size: 1.25
    weight: normal
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 2
    medium_size: 2.5
    large_size: 3
    weight: 700
    letter_spacing: -0.02
    line_height: 1.5
  h2:
    small_size: 2
    medium_size: 2.25
    large_size: 2.5
    weight: 700
    letter_spacing: -0.02
    line_height: 1.5
  h3:
    small_size: 1.5
    medium_size: 1.75
    large_size: 2
    weight: 700
    letter_spacing: -0.02
    line_height: 1.5
  h4:
    small_size: 1
    medium_size: 1.25
    large_size: 1.5
    weight: 700
    letter_spacing: 0
    line_height: 1.5
  h5:
    small_size: .75
    medium_size: 1
    large_size: 1.25
    weight: 700
    letter_spacing: 0
    line_height: 1.5
  h6:
    small_size: .75
    medium_size: .75
    large_size: 1
    weight: 700
    letter_spacing: 0
    line_height: 1.5
  p:
    small_size: 1
    medium_size: 1
    large_size: 1.25
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.5
  buttons:
    weight: 600
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""